// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SequenceItem { codon: Array<string>, anticodon: Array<string>, peptide: string | null, start_index: number, }