// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface DisplayCodon { nucleotides: Array<string>, anti_nucleotides: Array<string>, peptide: string | null, }