// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CursorData } from "./CursorData";
import type { SelectionData } from "./SelectionData";
import type { SequenceItem } from "./SequenceItem";

export interface SequenceData { sequence: Array<SequenceItem> | null, bp_count: number, cursor: CursorData, selection: SelectionData | null, }